apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terrance-java-web-app
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=terrance-java-web-app'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
